### ISSUE TITLE
Build Cargo requires update for aarch64

### ISSUE THREAD

**Issue by kingdonb** [AlanLang/excalidraw-wasm#30]
Hi, thanks for making this! I was able to get it to run on aarch64, but only with a `cargo update -p wasm-bindgen`

There is no aarch64 binary distro for wasm-bindgen at the release version you would have used over a year ago, when this was published. I don't know if you want a PR for cargo.lock, or if you are still using this project?

I really appreciate that you published this, I am thinking about building it into a Spin app - it was very easy to get running locally, maybe it will be just as easy to migrate the server to Fermyon Cloud! I am a Rubyist so I don't find many things that I would like to run which can be easily ported to wasm hosting, but excalidraw popped up on my radar this morning, and I quickly headed down the rabbit hole of "can I run this locally..." thanks to your release here, I now see that I definitely can, with very little fanfare needed.

**Comment by kingdonb** [comment]
I will go and learn Excalidraw now that I see it's very useful, above and beyond this minimal example. I would like to try hosting the full excalidraw-app in a wasm module next. Thanks for the inspiration!

**Comment by AlanLang** [comment]
Thank you very much! I hope the project https://github.com/AlanLang/excalidraw-rs can bring you more inspiration.
